= Introduksjon

2/1 Game Force eller bare "2 over 1" er et naturlig meldesystem som har disse hovedkjennetegn:

* beste minor
* 5-kort majoråpning
* 15-17 NT, kan innehold 5 kort major (5332-ish)
* 2 [.clubs]#♣# er sterkere enn normalt
* Mer aggressive sperremeldinger.

Navnet 2 over 1 kommer av at det blir etablert utgangskrav åpning 1 i farge, og svar i en lavere farge på to-trinnet. Dvs disse sekvensene:

* 1 [.diamonds]#♦# -> 2 [.clubs]#♣#
* 1 [.hearts]#♥# -> 2 [.clubs]#♣#
* 1 [.hearts]#♥# -> 2 [.diamonds]#♦#
* 1 [.spades]#♠# -> 2 [.clubs]#♣#
* 1 [.spades]#♠# -> 2 [.diamonds]#♦#
* 1 [.spades]#♠# -> 2 [.hearts]#♥#

Dette gjelder selvsagt IKKE i 3 og 4 posisjon når SH har passet først.

2 over 1 brukes ikke i disse situasjonene:

* Etter åpning 1 [.clubs]#♣#.
* Etter 1 [.diamonds]#♦# er alle andre svar enn 2 [.clubs]#♣# ikke GF.
* Når fienden melder inn eller dobler
* Etter åpning i 3. og 4. hånd

== Aggressivitet
Aggressiviteten gjelder både åpninger og innmeldinger.

I prioritert rekkefølge:

. Sone: Gunstig, Ingen, Alle, Ugunstig
. Posisjon: Tredje, Første, Andre
. Styrke/fordeling:
. I aggressive situasjoner:
.. 1-kort mindre i sperremeldinger
.. 1 taper mer eller færre hp i åpninger
.. mindre hp og/eller kvalitet i innmeldinger

== Videre meldinger etter 2-over-1

Når vi har etablert utgangskrav er det ikke lenger noen fare for at noen skal passe under utgang. Det er derfor ikke noen vits å hoppe for å vise gode kort. De fleste hopp er enten for å vise ensidig god farge, eller minimum.

=== Åpners gjenmelding

* *Gjenta egen farge:* ekstra lengde 6+, eller 5 solide.
* *Ny farge* viser 4-korts sidefarge, helst med litt kvalitet, gjentas med 5-5 fordeling.
* *Reverseringer:* ikke nødvendigvis ekstra styrke, kan være helt minimum, helst ikke en 8-tapers hånd.
* *2NT er en hvilemelding*. Har ingenting å melde, og makker kan ha sterke kort. Kan ha en 5-4-2-2 fordeling, men sidefargen er uten honnører. også naturlig..
* *Fast Arrival (hopp til utgang)* hvis du "vet" kontrakten og ikke har noe ekstra. Viser minimum og ikke noe annet fornuftig å melde. Fast Arrival brukes oftere i konkurranse enn når motparten ikke melder.
* *Hopp til 3NT* fra åpner viser en ekstremt svak åpning, og ingen andre farger å melde, mens hopp til 3NT fra svarhånden viser heller ingen andre farger å melde, og et svakt krav til utgang.
* *Hopp i ny farge* er ALDRI naturlig farge. Splinter i sidefargen til åpner. Minst 4-kort støtte og single/renons. Splinter kan utføres med minimumshender. Sleminteresse kan vises senere

Målet med det neste svaret er å beskrive "formen" på hånda uten å antyde styrke, MEN har man mindre enn forventet, hopp til utgang. Makker må ha ekstermt sterk hånd for å klare slem med åpners svake åpning. Meldingene er NATURLIG i de fleste tilfeller.

=== Åpners hoppmeldinger

* *Hopp i egen farge:* viser solid gående  farge (AKQJxx, AKQxxxx eller bedre). Hvis makker har 1 kort, så forventer vi at fargen skal stå helt til bunnen. "Hvis vi ikke ender opp i NT, så er min farge trumf". Viser bare gode kort i fargen, og ikke ekstra i sidefargene. Fortsett med cue-bids.
* *Hopp i ny farge:* Splinter med støtte til makkers farge
* *Hopp i 3 NT*, viser ingenting å melde og en svak åpning


=== Svarhåndens andre melding

* *Støtte til åpners farge*: 3-kort.
*.* *Hopp støtte i åpningsfarge:* Sterk hånd ca 15+. 3-kort støtte, god farge. Ber makker om kontrollmeldinger, mangel på cue viser svak hånd.

=== Etter 1 [.hearts]#♥# med 4-kort [.spades]#♠# og 4-kort minor

Vi foretrekker å etablere utgangskrav, og går gjerne forbi major fargen for å etablere 2-over-1. Husk, makker må vise formen sin først, vi vil finne evt major tilpass!

Altså: Hvis vi har 4-4 i ♠ og ♣, med verdier til utgang melder vi normalt 2♣  først, men med en sterkere 4-kort ♠ over en svak 4-korts ♣, så er det bedre å melde 1♠ først. Hjelper makker til ev. å finne en grand kontrakt.
