= Konkurransemeldinger

== De melder inn

=== Motparten dobler

|===
| melding | beskrivelse

| Redoble
| 10+. Etter redoble er alle doblinger straff!

| melding på en trinnet
| naturlig. Krav til runde, kan være mer enn 10+

| Melding på to-trinnet
| Naturlig. Ikke krav

| Hopp
| Sperr

| Hopp støtte
| Sperr

| que-bid
| limit raise
|===

== Vi melder inn

Dette er når motparten har åpnet og vi melder inn.

=== Vanlig innmelding

På en trinnet er det tilstrekkelig med en OK 5-kort farge. 6-16

På to trinnet, åpningsverdi med OK farge.

Hvis 17+ hender, doble først.

Etter innmelding er ny farge på en-trinnet ikke krav.
Ny farge på to-trinnet er krav til runde.

Cue-bid av åpners farge lover alltid 3 kort støtte. Invitt eller bedre

Hopp cue-bid av åpners farge viser 4-kort støtte og 7-9

=== Hoppinnmelding

I gunstig sone: Super-aggressiv.

Når makker har passet og vi har 6-kort farge hopp inn! Avhengig av sone selvsagt. Dette kan vi gjøre også opptil 12 hp, siden vi ikke skal i utgang!

=== Etter sterk NT (14+)

De fleste av fiendene har godt definerte NT-meldesekvenser. Det er derfor en forbrytelse å ikke forstyrre de så ofte man kan! Det er mange på lavt nivå som ikke har forsvar mot forsvarsmeldinger mot NT. Selv gode motspillere kommer fort ut på tynn is.

Vi bruker DONT (Disturbing Opponents No-Trump). Det er superenkelt, og effektivt. Det brukes både hvis man sitter rett etter åpner eller i 4 hånd: 1 NT -> Pass -> Pass.

Sone og posisjon er viktig. Vi melder ikke inn på med søppelfarger (feks Qxxx-Jxxx) i sonen.

Fokuset er å finne tilpass, det må ikke være i major. Vi sikter sjelden på utgang.

Tofargehender i denne forbindelsen er minst 4-4.

[cols="1,5"]
|===
|melding |beskrivelse

| D | En-farge hånd. Makker MÅ melde 2 [.clubs]#♣#. Deretter melder Dobler fargen sin
| 2 [.clubs]#♣# | 2 farge-hånd [.clubs]#♣# og høyere
| 2 [.diamonds]#♦# | 2 farge-hånd, [.diamonds]#♦# og høyere
| 2 [.hearts]#♥# | 2 farge-hånd, hjerter og spar
| 2 [.spades]#♠# | Naturlig, minst 5-kort, hvis man dobler først, makker melder 2 [.clubs]#♣# og man korrigerer til 2 [.spades]#♠# viser man bedre kort enn å melde 2 [.spades]#♠# direkte
|===

Regler for videre meldinger:

* Pass med 3+kort i fargen.
* Meld neste farge med 2-kortsfarge, deretter melder innbryter den andre fargen eller passer hvis den neste fargen er den andre fargen.
* Hvis innmelding er 2 [.diamonds]#♦#, og makker har 4-4 i major, melder man 2 [.hearts]#♥#, og innbryter korrigerer hvis den andre fargen er spar. Pass med 3+ kort.
* Hvis innmelding er 2 [.hearts]#♥#, prefererer makker med pass eller 2 [.spades]#♠#.
* Hvis to-farge DONT meldingen blir doblet: Pass=villig til å spille. RD=meld din andre farge, Ny farge=Jeg vil heller spille i denne fargen (skal alltid passes)!

Husk: Vi er stort sett ikke interessert i utgang. Men hvis man en gang i skuddåret er interessert, kan makker melde 2 NT, hvor innmelder skal vise sin hånd etter følgende metode.

* Hvis innbryter sa 2 [.clubs]#♣#, melder hen 3 [.clubs]#♣# med minimum, den andre fargen med max.
* Hvis innmelding var 2 [.diamonds]#♦# viser 3 [.clubs]#♣#/3 [.diamonds]#♦# minimum, og sidefarge i hhv [.hearts]#♥# / [.spades]#♠# og 3 [.hearts]#♥# / [.spades]#♠# med max.
* Hvis innmelding var 2 [.hearts]#♥#, melder man 3 [.clubs]#♣#/[.diamonds]#♦# med minimum, samtidig som man viser sin beste farge og 3 [.hearts]#♥# / [.spades]#♠# med max.

Alle meldingene over må alerteres!

=== Etter svak NT (under 14, feks 13-15 )

|===
| melding | beskrivelse

| D | God hånd, minst tilsvarende åpner.
|===


=== Etter svake 2 fra de

X = Takeout, selv etter 4 [.spades]#♠#, men kan passes ut for business av makker.

==== Lebensohl etter dobling av svake 2

Etter dobling av sperr er 2 NT Lebensohl: "Jeg har en svak hånd", rele til 3 [.clubs]#♣#, deretter vises farge. Direkte melding på 3-trinnet viser en bedre hånd. Minst invitt. Hvis dobler har en "stor" hånd, kan han melde noe annet enn 3 [.clubs]#♣#.

Hvis DOBLER har passet først er 2 NT scrambling til minor, ikke Lebensohl

=== Michaels cue-bid

Eksempel: (1 [.spades]#♠#) - 2 [.spades]#♠#

Viser 0-10 eller 15+. minst 5-5 i fargene

I minor: Begge major.
Makker prefererer farge eller melder 2NT = hvilken hånd har du?
Cue-bidder melder 3 [.hearts]#♥# med 5-10 (fast arrival), 3 [.clubs]#♣# / [.diamonds]#♦# med 15+, viser den beste fargen

I major: Minst 5-5 i den andre major + en minor.
2 NT er spørsmål etter minoren. Hvis 2 NT melderen deretter melder majoren er det invitt.

=== Unusual NT

Minst 5-5 i de to laveste umeldte fargene. 0-10 eller 15+. Ikke midt-i-mellom styrke. Meld da vanlig.

Når?

* Fienden har åpnet,
* Det finnes minst to umeldte farger.
* Ingen av oss har meldt noe eller doblet.
* Etter at de har åpnet i en og støttet i to: (1 [.hearts]#♥#) - P - 2 ([.hearts]#♥#)

Hvis de dobler unusual 2NT er P = lik lengde i fargene til makker.

3 NT er aldri Unusual.

==== På høyt nivå
Eksempler

[cols="1,1,1,1,4"]
|===
| N | Ø | S | V | beskrivelse

|4 [.hearts]#♥# | 4 NT | | | begge minor
|1 [.spades]#♠# | X | 4 [.spades]#♠# | 4 NT | kan være 5-5 i to farger +
 Scrambler til beste fit.
|===

(4 [.hearts]#♥#) - 4 NT = unusual. Stort sett bare i gunstig sone?

==== Svar på unusual

Makker melder vanligvis den beste av de to fargene. Hvis lik, meld den billigste.

Hopp i en av fargene: Sperr ifølge Loven.

Melding av den fjerde fargen, naturlig, ikke krav. min 6-kort, ingen tilpass til unusual melderen.

=== Forsvar mot unusual/Michaels

Vi skiller mellom der det er en eller to kjente farger

==== En kjent farge

|===
| D | straffe-orientert, alle senere doblinger er straffeforslag
| cue-bid | limit raise (10+) med minst 3-kort støtte. Hvis sleminteresse, vises det senere
| støtte | 7-10 3+støtte
|===

==== To kjente farger

|===
| D | straffe-orientert, alle senere doblinger er straffeforslag
| laveste cue-bid | minst invitt, med den fjerde fargen.
| høyeste cue-bid | minst invitt, 3+ støtte
| støtte | 7-10, og 3+ støtte
|===

==== Eksempler forsvar mot unusual/Michaels

[cols="1,1,1,5"]
|===
| N | Ø | S | S viser

| 1 [.clubs]#♣# | 2 [.clubs]#♣# | X | straffe-sugen
| 1 [.clubs]#♣# | 2 [.clubs]#♣# | 2 [.diamonds]#♦# | [.diamonds]#♦#, ikke krav
| 1 [.clubs]#♣# | 2 [.clubs]#♣# | 2 [.hearts]#♥# | [.diamonds]#♦#, invitt styrke
| 1 [.clubs]#♣# | 2 [.clubs]#♣# | 2 [.spades]#♠# | [.clubs]#♣#-støtte invitt+
| 1 [.diamonds]#♦# | 2 [.diamonds]#♦# | 2 [.hearts]#♥# | [.clubs]#♣#, invitt
| 1 [.hearts]#♥# | 2 NT | 3 [.diamonds]#♦# | [.hearts]#♥#-støtte, invitt+
| 1 [.spades]#♠# | 2 [.spades]#♠# | 3 [.hearts]#♥# | [.spades]#♠#-støtte, invitt+
| 1 [.spades]#♠# | 2 [.spades]#♠# | 3 [.spades]#♠# | [.spades]#♠#-støtte, 7-10
| 1 [.spades]#♠# | 2 NT | 3 [.hearts]#♥# | som svake 2 [.hearts]#♥#


|===
