= 1 NT Forcing

Dette er ulempen med 2/1. Man må opprette en melding som man kan bruke for å vise en rekke ulike hender. 1 NT er denne meldingen.

1 NT forcing er som navnet antyder ABSOLUTT krav til runde.

Etter majoråpning er svar 1 NT en "sekkemelding" som viser 6-12 hp. Du kan IKKE ha 4-kort støtte. Vi kan ikke melde lavere farger på to-trinnet siden det er GF.

Etter 1 [.hearts]#♥# benekter den også 4-kort spar?

== Åpners svar på 1 NT forcing

|===
| svar | beskrivelse

| 2 [.clubs]#♣#/[.diamonds]#♦#
| Minst 3-kort farge. +
NB! 2 [.clubs]#♣# KAN vise nøyaktig 4-5-2-2 fordeling, altså 2-kort farge i kløver hvis man ikke har styrke til revers melding. +
1 [.hearts]#♥# -> 1 NT -> 2 [.spades]#♠# er revers og viser ekstra verdier.

| 2 i motsatt major
| minst 4-kort.

| 2 i åpningsfargen
| 6+ kort. Ikke krav.

| 2 NT
| Sterk NT, balansert. Altså 17+

| 3 trinnet
| Som vanlig
|===

Eksempler etter 1 [.spades]#♠# -> 1 NT:

|===
| A | B | C | D | E

| [.spades]#♠# A Q 9 8 2
| [.spades]#♠# Q J 10 6 5 2
| [.spades]#♠# A K Q 5 2
| [.spades]#♠# A J 5 4 2
| [.spades]#♠# A Q J 10 5 4 2

| [.hearts]#♥# A 5 2
| [.hearts]#♥# A 5 2
| [.hearts]#♥# A K Q 10 2
| [.hearts]#♥# A K 2
| [.hearts]#♥# A J 2

| [.diamonds]#♦# Q J 2
| [.diamonds]#♦# Q J 2
| [.diamonds]#♦# 10 5 2
| [.diamonds]#♦# K 2
| [.diamonds]#♦# K 2

| [.clubs]#♣# 7 3
| [.clubs]#♣# A
| [.clubs]#♣# -
| [.clubs]#♣# K 8 3
| [.clubs]#♣# 3

|===

Svar:

A. 2 [.diamonds]#♦#
B. 2 [.spades]#♠#. Viser 6 kort og minimum
C. 3 [.hearts]#♥#. Naturlig hopp. GF.
D. 2 NT. 18-19. balansert
E. 4 [.spades]#♠#. Ekstra lengde. Ekstra poeng.

Legg merke til at alle svar unntatt A er som i normale system. Med A ville man ha passet i andre systemer.

== Videre meldinger etter 1 NT forcing

|===
| melding | beskrivelse

| Ny farge på to-trinnet
| Naturlig. Ikke krav

| Støtte i åpningsfargen
| Farge-preferanse. Normalt 2-korts støtte. 6-9 hp +
Men kan også være en elendig 3-korts støtte 5-6 hp. Godt alternativ til å passe åpningen.

| 2 NT
| Invitt. Naturlig

| Høyning i åpningsfargen
| Naturlig invitt. 5+ kort

| Hopp støtte i åpningsfargen
| 3 kort støtte. 10-12 hp
|===

Eksempler. Etter 1 [.spades]#♠# -> 1 NT -> 2 [.clubs]#♣#

|===
| A | B | C | D | E

| [.spades]#♠# 6
| [.spades]#♠# A 5 2
| [.spades]#♠# Q 7
| [.spades]#♠# 10
| [.spades]#♠# 4

| [.hearts]#♥# 10 3 2
| [.hearts]#♥# Q J 9 8 2
| [.hearts]#♥# A Q 6 2
| [.hearts]#♥# Q 10 9 8 7
| [.hearts]#♥# K Q 10 8 7 6

| [.diamonds]#♦# Q 5 4 2
| [.diamonds]#♦# K 10 2
| [.diamonds]#♦# 9 8 7 6
| [.diamonds]#♦# K Q 10 8 7
| [.diamonds]#♦# Q 4 3 2

| [.clubs]#♣# A K J 6 4
| [.clubs]#♣# 10 9
| [.clubs]#♣# 5 4 2
| [.clubs]#♣# A 8 2
| [.clubs]#♣# J 2
|===

A. 3 [.clubs]#♣#. Støtte invitt
B. 3 [.spades]#♠#. 3 kort 10-12hp
C. 2 [.spades]#♠#. Normalt 2-kort, men også 3-kort "søppel-hånd"
D. 2 NT. Naturlig invitt
E. 2 [.hearts]#♥#. Naturlig ikke krav.
