== Walsh diamond

Når:: Kun etter 1 [.clubs]#♣# åpning.

Hvordan::
* med svak hånd(under 12 hp) og 4+ ruter, og 4+ major hopper vi over [.diamonds]#♦# og melder majoren.
* med sterk hånd(12+ hp) og 4+ ruter, og 4+ major melder vi [.diamonds]#♦# først og melder majoren senere. Detter er utgangskrav.
* Når vi har en svak hånd med minst 7 ruter og en _svak_ major, da _kan_ vi melde ruteren først.
* Etter 1 [.clubs]#♣# - 1 [.diamonds]#♦#, hopper svarhånden også over major med jevnish hånd.
* Hvis ÅH melder major etter 1 [.clubs]#♣# - 1 [.diamonds]#♦#, viser det en ubalansert hånd.
* Altså; med både ruter og en majorfarge, vil vi kun melde ruteren først hvis vi kan kreve til utgang, ellers melder vi 4-korts major.
* 1 [.clubs]#♣# - 1 [.diamonds]#♦# benekter _vanligvis_ 4-korts major. Hvis den ikke benekter major, har man verdier til utgang.

NB! Både 1 [.diamonds]#♦# / 1 [.hearts]#♥# / 1 [.spades]#♠# skal alerteres

Dette innebærer også at 1 [.clubs]#♣# - 1 [.hearts]#♥#
 /1 [.spades]#♠#; 1NT - 2 [.diamonds]#♦# viser 4-korts major og normalt 5-6 korts ruter og svak hånd.

ÅH sin andre melding er normalt basert på fordeling. Har man grandfordeling, så meldes ikke eventuell(e) 4-korts major(er) etter at vi har startet med 1 [.clubs]#♣# -> 1 [.diamonds]#♦#.

Unntak::
* Hvis man har 4-4-3-2 fordeling og alle poengene i 4-korts fargene, så er det bedre å melde farge framfor fordeling.

OBS:: Etter 1 [.clubs]#♣# - 1 [.hearts]#♥# vil ÅH melde 1 [.spades]#♠# også med flat minimum.

Se https://www.bridgehands.com/W/Walsh_Diamond_Responses.htm[her for nærmere detaljer]

|===
| melding | beskrivelse

| 1 [.clubs]#♣# - 1 [.diamonds]#♦#
|


|===