= Nøyaktig 4 kort støtte: Bergen raises

Bergen raises er basert på https://www.bridgebum.com/law_of_total_tricks.php[Law of Total Tricks], som sier at man kan spille til det nivået man har nok trumf til. Har man ni trumf kan man melde 3.

Bergen raises oppstår etter åpning i 1 major farge og farge svar på 3-trinnet.

Det er ikke alle som liker denne!

Bergen raises er kun på hvis pass eller doble fra fienden. Ellers ikke.

Ideen er:

* Vi ikke har nok rom verdier til å kreve til utgang, da bruker vi andre metoder.
* Eller vi har krav til utgang og en single/renons.
* Vi vet hvilken trumf vi kan spille, og vi har minst 9 stk. Ifølge Loven.
* Vi sperrer motparten til venstre ute fra hele to-trinnet. Vanskeligere å komme inn

== Meldinger etter Bergen raises

=== Etter 3 [black]#♣#
3 [black]#♣# viser 4-kort støtte og 7-9. "Konstruktiv støtte".

|===
| melding | Beskrivelse

| 3 [red]#♦#
| Viser sidefarge. Interesse for utgang. +
Åpner slår av i 3 major med minimum. +
Åpner melder utgang med max.

| 3 [red]#♥#
| Hvis major er [red]#♥# = Avslag +
Hvis major er [black]#♠# = sidefarge. Invitt.

| 3 [black]#♠#
| Hvis major er [black]#♠# = Avslag +
Hvis major er [red]#♥# = Sterk og naturlig med interesse for slem. Svarhånda forventes å oppføre seg intelligent. Avslå med utgang, eller cue-bids
|===

=== Etter 3 [red]#♦#

3 [red]#♦# viser 10-12 og 4-kort støtte.

|===
| melding | beskrivelse

| 3 [red]#♥#
| Hvis major er [red]#♥# = Avslag +
Hvis major er [black]#♠# = Sidefarge med interesse for utgang

| 3 [black]#♠#
| Hvis major er [black]#♠# = Avslag +
Hvis major er [red]#♥# = Sterk naturlig med interesse for slem.
|===

=== Etter sperr i major

1 [red]#♥# -> 3 [red]#♥# viser 4 kort støtte og 0-6 poeng. Sperrebetont.

|===
| melding | beskrivelse

| Pass
| Javel! Mindre enn 18 hp

| 4 M
| Vi knaller til! 18+
|===

=== Åpners melding etter 1 [black]#♠# -> 3 [red]#♥#

Denne meldingen viser en kortfarge og 4-kort støtte. Krav til utgang.

|===
| melding | beskrivelse

| 3 [black]#♠#
| Rele. Spør etter kortfargen +
3 NT = kortfarge [black]#♣# +
4 [black]#♣# kortfarge [red]#♦# +
4 [red]#♦# kortfarge [red]#♥#

| 4 [black]#♠#
| Avslag
|===

Eksempel etter 1 [red]#♥# -> 3 [black]#♠#:

|===
| Åpner | Svarer

| [black]#♠# A5 | [black]#♠# KQ42
| [red]#♥# AK843 | [red]#♥# QJ52
| [red]#♦# DKJT9 | [red]#♦# 5
| [black]#♣# T5 | [black]#♣# A983

| meldinger
|

| 1 [red]#♥# | 3 [black]#♠# (1)
| 3 NT (2) | 4 [red]#♦# (3)
| 4 [red]#♥# (4)
|===

1. GF. 4-kort støtte. Ukjent kortfarge
2. Javel, jeg kan være interessert i slem! Hvilken kort farge har du?
3. Rutern min er kort!
4. Fan, da har jeg bortkastede verdier i ruter. Hvorfor var du ikke kort i kløver istedet?

=== Åpners melding etter 1 [red]#♥# -> 3 [black]#♠#

Denne meldingen viser en kortfarge og 4-kort støtte. Krav til utgang.

|===
| melding | beskrivelse

| 3 NT
| Rele. Spør etter kortfargen +
4 [black]#♣# / [red]#♦# / [red]#♥# viser den.

| 4 hj
| Avslag
|===

