= Fast Arrival prinsippet

De fleste 2-over-1 brukere bruker Fast Arrival prinsippet når utgangskrav er etablert.

[quote, Marty Bergen: Better Bidding with Bergen volume two ]
When we agree on a trump suit and is in a forcing auction, bidding the trump suit at the level we are forced to shows the least forward-going type of hand.

* Hopp direkte til utgang er den svakeste meldingen.
* Saktere framgangsmetoder kan være sleminteresse.

== Utenfor konkurranse

=== Eksempler med støtte

|===
|Åpner |Svarer

|1 [.spades]#♠#
|2 [.hearts]#♥#

|2 NT
|4 [.spades]#♠#
|===

|===
|Åpner |Svarer

|1 [.spades]#♠#
|2 [.hearts]#♥#

|2 NT
|3 [.spades]#♠#
|===

Den første meldingssekvensen viser minimum. "Jeg har minimum. Vi har funnet trumf og det er ingen vits å lete etter slem".

NOTE: Åpner kan ha andre planer! Hvis kruttsterk, that is!

I den andre har svarer bedre kort enn i den første, og holder mulighetene åpne for slem. "Jeg har sparstøtte og ekstra verdier, kjør cue-bids / RKC".

NOTE: Det er en viktig regel: Når svarhånden støtter makker i sin andre melding har hun ALLTID 3-kort støtte. Ikke 2-kort. Det er ingen hensikt med farge-preferanse.

I begge eksemplene over viser 3-kort støtte, men i siste eksempel også ekstra verdier.

NOTE: Det er vanlig å ikke bruke Fast Arrival til NT. Det må avtales spesifikt. Kan tas senere.

=== Eksempler uten støtte

|===
| Åpner | Svarer

| 1 [.spades]#♠# | 2 [.clubs]#♣#
| 2 [.diamonds]#♦# | ?
|===

|===
| A | B |C

|[.spades]#♠# K 8
|[.spades]#♠# Q 7
|[.spades]#♠# A 7

|[.hearts]#♥# K J 7
|[.hearts]#♥# 8 7 6
|[.hearts]#♥# 5 4 2

|[.diamonds]#♦# K 8 7
|[.diamonds]#♦# K 2
|[.diamonds]#♦# A Q 2

|[.clubs]#♣# A J 10 8 7
|[.clubs]#♣# A Q J 10 9 2
|[.clubs]#♣# A 10 8 7 6
|===

A. 2NT. Stoppere i umeldte
B. 3 [.clubs]#♣#. Ekstra lengde
C. 3 [.diamonds]#♦#. Denne er vanskelig. I normale systemer ville man ha meldt 2 [.hearts]#♥# som "kunstig fjerde farge krav". 3 [.diamonds]#♦# er nødmelding på 3-kort støtte. Viser vanligvis 4-kort støtte.

Hvis svarer hopper til utgang i _egen_ farge viser det også minimum og sign off. Fast Arrival. Lang farge.

Hva så med hopp til 3 NT? De fleste 2-over-1 brukere bruker ikke Fast Arrival til NT fordi det forstyrrer leting etter tilpass. Men inntil videre kan vi bruke det for konsistens.

== I konkurranse

|===
| N | Ø | S | V

| 1 [.diamonds]#♦# | 1 [.spades]#♠# | 2 [.spades]#♠# <1> | 3 [.clubs]#♣#
| ?
|===

1. 2 [.spades]#♠# er limit raise or better, setter opp krav til minst 3 [.diamonds]#♦#
2. e

== Quiz 1

Hva skal du melde etter:
|===
| Åpner | Svarer

| 1 [.spades]#♠# | 2 [.clubs]#♣#
| 2 [.diamonds]#♦# | ?
|===

|===
|A|B|C|D|E

|[.spades]#♠# Q 2
|[.spades]#♠# K 3 2
|[.spades]#♠# 5
|[.spades]#♠# 8 7
|[.spades]#♠# K 7 6

|[.hearts]#♥# A Q J 3
|[.hearts]#♥# A 5 4
|[.hearts]#♥# A 2
|[.hearts]#♥# K J 5
|[.hearts]#♥# A 2

|[.diamonds]#♦# Q 2
|[.diamonds]#♦# A 2
|[.diamonds]#♦# K Q 4 3
|[.diamonds]#♦# K J 7
|[.diamonds]#♦# Q 5 2

|[.clubs]#♣# A 7 6 5 4
|[.clubs]#♣# K Q J 8 7
|[.clubs]#♣# A 7 6 5 4 2
|[.clubs]#♣# A J 7 6 4
|[.clubs]#♣# K J 8 7 6
|===

A. 2 [.hearts]#♥#. Naturlig
B. 2 [.spades]#♠#. 3-kort-støtte.
C. 3 [.diamonds]#♦#. Støtt med støtte
D. 3 NT. Stoppere og flat hånd. Hvis man ikke bruker Fast Arrival til NT (som er vanlig), så melder man 2 NT.
E. 4 [.spades]#♠#. 3 kort og minimum

== Quiz 2

Hva melder du etter

|===
|Åpner |Svarer

|1 [.hearts]#♥#
|2 [.diamonds]#♦#

|2 [.hearts]#♥#
|?
|===


|===
| A |B |C 

|[.spades]#♠# 4 3
|[.spades]#♠# K Q 7 6
|[.spades]#♠# J 4

|[.hearts]#♥# A Q 2
|[.hearts]#♥# 2
|[.hearts]#♥# J 5 4

|[.diamonds]#♦# A Q J 8 6
|[.diamonds]#♦# K Q J 8 7 6
|[.diamonds]#♦# K Q J 10 8 7

|[.clubs]#♣# Q J 4
|[.clubs]#♣# A 2
|[.clubs]#♣# A J
|===

A. 3 [.hearts]#♥#. Tre kort støtte og tillegg
B. 2 [.spades]#♠#. 4-kort. Makker kan være 6-4 i major
C. 4 [.hearts]#♥#. Fast Arrival. 3-kort støtte, minimum


== Oppsummering Fast Arrival

* Alle hopp til utgang viser minimumshender, den svakeste meldingen
* Vi kan også bruke motsatt strategi for hopp til 3 NT. Men det krever ekstra avtaler.
* Det er vanlig å bruke et unntak for Fast Arrival: 1x -> 2y -> 2z - 3 NT (viser rundt 16-17, altså ekstra. Dette må i såfall avtales som et unntak)

