name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Setup gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  cache-read-only: false
            - name: Build with gradle
              run: ./gradlew asciidoctor asciidoctorPdf
            - name: Setup pages
              #if: github.ref == 'refs/heads/master'
              uses: actions/configure-pages@v5
            - name: Upload pdf files as artifact
              id: pdf-deployment
              uses: actions/upload-artifact@v4
              with:
                name: 2-over-1-pdf
                path: build/docs/asciidocPdf/2-over-1.pdf
            - name: Upload html files as pages artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: build/docs/asciidoc
    deploy-pages:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to github pages
              id: deployment
              uses: actions/deploy-pages@v4


