name: Build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Setup gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Build with gradle
              run: ./gradlew asciidoctor asciidoctorPdf
            - name: Setup pages
              #if: github.ref == 'refs/heads/master'
              uses: actions/configure-pages@v5
    upload-pdf-artifact:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/upload-artifact@v4
              with:
                name: 2-over-1-pdf
                path: build/docs/asciidocPdf/2-over-1.pdf
    upload-html-artifact:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/upload-pages-artifact@v3
              with:
                name: github-pages
                path: build/docs/asciidoc/
    deploy-pages:
        runs-on: ubuntu-latest
        needs: upload-html-artifact
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to github pages
              #if: github.ref == 'refs/heads/master'
              uses: actions/deploy-pages@v4


