name: build-system
on: [push]
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup java 21 for x64
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'zulu'
                  # architecture: 'x64'
                  cache: 'gradle'
            - run: ./gradlew asciidoctorPdf
            - uses: actions/upload-artifact@v3
              name: 2-over-1
              with:
                  path: build/docs/asciidocPdf/2-over-1.pdf


